//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;


namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {   [Required]
        [Display(Name="User Name:")]

        public string username { get; set; }

        [Required]
        [Display(Name="Password:")]
        public string password { get; set; }
    }
}
